name: Linux

on:
  push:
    branches:
      - "master" 
      # - "dev-ci"
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  
  build-native:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: ForeFire build
        run: sudo bash ./install-forefire.sh -y

      - name: Check version
        run: ./bin/forefire -v

      # - name: Test
      #   run: cd tests && bash run.bash